/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TakedownRouteImport } from './routes/takedown'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as GuardianTokenRouteImport } from './routes/guardian.$token'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TakedownRoute = TakedownRouteImport.update({
  id: '/takedown',
  path: '/takedown',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianTokenRoute = GuardianTokenRouteImport.update({
  id: '/guardian/$token',
  path: '/guardian/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/guardian/$token': typeof GuardianTokenRoute
  '/messages/$id': typeof MessagesIdRoute
  '/u/$id': typeof UIdRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/guardian/$token': typeof GuardianTokenRoute
  '/messages/$id': typeof MessagesIdRoute
  '/u/$id': typeof UIdRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/guardian/$token': typeof GuardianTokenRoute
  '/messages/$id': typeof MessagesIdRoute
  '/u/$id': typeof UIdRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/signup'
    | '/takedown'
    | '/terms'
    | '/guardian/$token'
    | '/messages/$id'
    | '/u/$id'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/signup'
    | '/takedown'
    | '/terms'
    | '/guardian/$token'
    | '/messages/$id'
    | '/u/$id'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/signup'
    | '/takedown'
    | '/terms'
    | '/guardian/$token'
    | '/messages/$id'
    | '/u/$id'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TakedownRoute: typeof TakedownRoute
  TermsRoute: typeof TermsRoute
  GuardianTokenRoute: typeof GuardianTokenRoute
  MessagesIdRoute: typeof MessagesIdRoute
  UIdRoute: typeof UIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takedown': {
      id: '/takedown'
      path: '/takedown'
      fullPath: '/takedown'
      preLoaderRoute: typeof TakedownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/$token': {
      id: '/guardian/$token'
      path: '/guardian/$token'
      fullPath: '/guardian/$token'
      preLoaderRoute: typeof GuardianTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TakedownRoute: TakedownRoute,
  TermsRoute: TermsRoute,
  GuardianTokenRoute: GuardianTokenRoute,
  MessagesIdRoute: MessagesIdRoute,
  UIdRoute: UIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
